INSERT INTO recipe (name, description, ingredients, steps, categories) VALUES ('Broccoli Pesto Pasta', 'This broccoli pesto recipe offers up a delicious solution—broccoli florets that are whizzed right into the pesto sauce itself, adding an even more vibrant punch of emerald green to the sauce as well as a serious nutritional boost. In addition to being a great source of fiber, this dark green member of the brassica family boasts lots of vitamin C and vitamin A, as well as some iron, calcium and potassium. Blended into a classic pesto along with some of the pasta cooking water, broccoli gives this pesto sauce just a bit of creaminess and a lot more oomph.', 'Broccoli florets, Fresh basil, Fresh garlic, Pine nuts, Extra virgin olive oil, Parmigiano-Reggiano, And one secret ingredient: reserved pasta cooking water', 'Prep all of your broccoli pesto ingredients—rinse the basil leaves, grate your Parmigiano, peel your garlic. Bring a big pot of salted water to a boil. Boil the broccoli. After two minutes, remove the florets, and add your pasta. While the pasta cooks, make the pesto! Blend the broccoli, basil, garlic, pine nuts, extra virgin olive oil, salt and parmigiano reggiano until it’s nice and smooth. When the pasta is done, scoop out a cup of that liquid gold (aka pasta water) and add it slowly to the pesto as you blend it a bit more. Toss the pasta with the broccoli pesto and dig in!', 'dinner,pasta,healthy');

INSERT INTO recipe (name, description, ingredients, steps, categories) VALUES ('Lemon Chicken', 'Lemon chicken is really just a simple baked chicken recipe, jazzed up with some punchy ingredients that add lots of flavor without taking away from how super-healthy baked chicken breasts are. Our lemon chicken recipe is fast and easy—a recipe you might turn to on a busy weeknight when you need dinner to be simple as it can be.', 'Lemon, three ways. We aren’t messing around—this isnt just lemon chicken. It’s LEMON chicken! We use lemon zest, fresh-squeezed lemon juice and whole lemon slices to give this lemon chicken recipe all of the citrusy punch that we possibly can. Garlic, two ways. We could maybe have called this lemon garlic chicken, since our recipe calls for both fresh garlic cloves and (you guessed it) our beloved garlic powder. Herbs, herbs and more herbs. A whole garden’s worth of fragrance and flavor, all from a few dried herbs that you probably already have in your pantry.', 'Make a lemon chicken marinade. Well, it’s really more like a rub or a paste, because our lemon chicken recipe requires no actual marinating (yay!). But basically, we coat the chicken breasts in a thick, olive oil-based herb paste flavored with oregano, thyme, garlic powder, salt and pepper. Make the lemon chicken sauce! Stir together all of the zingy things—white wine, fresh garlic, lemon zest, lemon juice—to make the sauce that the chicken breasts will bake in. You’ll also use this sauce to baste the chicken as it bakes, ensuring that these bright flavors have a chance to be absorbed by the chicken (without having to actually marinate the chicken). Bake! Until you get that internal temperature reading of 165°F. Then it’s time to dig in!', 'dinner, healthy');

INSERT INTO category (value) VALUES ('dinner');
INSERT INTO category (value) VALUES ('pasta');
INSERT INTO category (value) VALUES ('healthy');

INSERT INTO recipecategories (recipe_id, category_id) VALUES (1, 1);
INSERT INTO recipecategories (recipe_id, category_id) VALUES (1, 2);
INSERT INTO recipecategories (recipe_id, category_id) VALUES (1, 3);
INSERT INTO recipecategories (recipe_id, category_id) VALUES (2, 1);
INSERT INTO recipecategories (recipe_id, category_id) VALUES (2, 3);
